<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20141009225031 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE famelo_soul_domain_model_abstractfragment DROP FOREIGN KEY FK_3D10774D09FCB3");
		$this->addSql("ALTER TABLE famelo_soul_domain_model_abstractfragment ADD CONSTRAINT FK_3D10774D09FCB3 FOREIGN KEY (soul) REFERENCES famelo_soul_domain_model_soul (persistence_object_identifier) ON DELETE CASCADE");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE famelo_soul_domain_model_abstractfragment DROP FOREIGN KEY FK_3D10774D09FCB3");
		$this->addSql("ALTER TABLE famelo_soul_domain_model_abstractfragment ADD CONSTRAINT FK_3D10774D09FCB3 FOREIGN KEY (soul) REFERENCES famelo_soul_domain_model_soul (persistence_object_identifier)");
	}
}