<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20141009232239 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("DROP TABLE famelo_soul_domain_model_controllerfragment");
		$this->addSql("DROP TABLE famelo_soul_domain_model_emailverificationfragment");
		$this->addSql("DROP TABLE famelo_soul_domain_model_fragment");
		$this->addSql("ALTER TABLE famelo_soul_domain_model_abstractfragment ADD controller VARCHAR(255) DEFAULT NULL, ADD action VARCHAR(255) DEFAULT NULL");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("CREATE TABLE famelo_soul_domain_model_controllerfragment (persistence_object_identifier VARCHAR(40) NOT NULL, controller VARCHAR(255) NOT NULL, action VARCHAR(255) NOT NULL, PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE famelo_soul_domain_model_emailverificationfragment (persistence_object_identifier VARCHAR(40) NOT NULL, PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE famelo_soul_domain_model_fragment (persistence_object_identifier VARCHAR(40) NOT NULL, PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("ALTER TABLE famelo_soul_domain_model_controllerfragment ADD CONSTRAINT FK_8AFF3DAB47A46B0A FOREIGN KEY (persistence_object_identifier) REFERENCES famelo_soul_domain_model_abstractfragment (persistence_object_identifier) ON DELETE CASCADE");
		$this->addSql("ALTER TABLE famelo_soul_domain_model_emailverificationfragment ADD CONSTRAINT FK_8C363B4C47A46B0A FOREIGN KEY (persistence_object_identifier) REFERENCES famelo_soul_domain_model_abstractfragment (persistence_object_identifier) ON DELETE CASCADE");
		$this->addSql("ALTER TABLE famelo_soul_domain_model_fragment ADD CONSTRAINT FK_289AEDCA47A46B0A FOREIGN KEY (persistence_object_identifier) REFERENCES famelo_soul_domain_model_abstractfragment (persistence_object_identifier) ON DELETE CASCADE");
		$this->addSql("ALTER TABLE famelo_soul_domain_model_abstractfragment DROP controller, DROP action");
	}
}