<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20141009225124 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE famelo_soul_domain_model_soul DROP FOREIGN KEY FK_288DD06D53A4BC5B");
		$this->addSql("ALTER TABLE famelo_soul_domain_model_soul ADD CONSTRAINT FK_288DD06D53A4BC5B FOREIGN KEY (rootfragment) REFERENCES famelo_soul_domain_model_abstractfragment (persistence_object_identifier) ON DELETE SET NULL");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE famelo_soul_domain_model_soul DROP FOREIGN KEY FK_288DD06D53A4BC5B");
		$this->addSql("ALTER TABLE famelo_soul_domain_model_soul ADD CONSTRAINT FK_288DD06D53A4BC5B FOREIGN KEY (rootfragment) REFERENCES famelo_soul_domain_model_abstractfragment (persistence_object_identifier)");
	}
}