<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20141010204640 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE famelo_soul_domain_model_abstractfragment_children_join DROP FOREIGN KEY FK_BAA6D7F160D73502");
		$this->addSql("ALTER TABLE famelo_soul_domain_model_abstractfragment_children_join DROP FOREIGN KEY FK_BAA6D7F18146364F");
		$this->addSql("ALTER TABLE famelo_soul_domain_model_soul DROP FOREIGN KEY FK_288DD06D53A4BC5B");
		$this->addSql("DROP TABLE famelo_soul_domain_model_abstractfragment");
		$this->addSql("DROP TABLE famelo_soul_domain_model_abstractfragment_children_join");
		$this->addSql("DROP INDEX UNIQ_288DD06D53A4BC5B ON famelo_soul_domain_model_soul");
		$this->addSql("ALTER TABLE famelo_soul_domain_model_soul ADD identifier VARCHAR(255) NOT NULL, ADD activefragment VARCHAR(255) NOT NULL, DROP rootfragment");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("CREATE TABLE famelo_soul_domain_model_abstractfragment (persistence_object_identifier VARCHAR(40) NOT NULL, soul VARCHAR(40) DEFAULT NULL, dtype VARCHAR(255) NOT NULL, controller VARCHAR(255) DEFAULT NULL, action VARCHAR(255) DEFAULT NULL, INDEX IDX_3D10774D09FCB3 (soul), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE famelo_soul_domain_model_abstractfragment_children_join (soul_abstractfragment VARCHAR(40) NOT NULL, child_inverse_id VARCHAR(40) NOT NULL, INDEX IDX_BAA6D7F18146364F (soul_abstractfragment), INDEX IDX_BAA6D7F160D73502 (child_inverse_id), PRIMARY KEY(soul_abstractfragment, child_inverse_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("ALTER TABLE famelo_soul_domain_model_abstractfragment ADD CONSTRAINT FK_3D10774D09FCB3 FOREIGN KEY (soul) REFERENCES famelo_soul_domain_model_soul (persistence_object_identifier) ON DELETE CASCADE");
		$this->addSql("ALTER TABLE famelo_soul_domain_model_abstractfragment_children_join ADD CONSTRAINT FK_BAA6D7F160D73502 FOREIGN KEY (child_inverse_id) REFERENCES famelo_soul_domain_model_abstractfragment (persistence_object_identifier)");
		$this->addSql("ALTER TABLE famelo_soul_domain_model_abstractfragment_children_join ADD CONSTRAINT FK_BAA6D7F18146364F FOREIGN KEY (soul_abstractfragment) REFERENCES famelo_soul_domain_model_abstractfragment (persistence_object_identifier)");
		$this->addSql("ALTER TABLE famelo_soul_domain_model_soul ADD rootfragment VARCHAR(40) DEFAULT NULL, DROP identifier, DROP activefragment");
		$this->addSql("ALTER TABLE famelo_soul_domain_model_soul ADD CONSTRAINT FK_288DD06D53A4BC5B FOREIGN KEY (rootfragment) REFERENCES famelo_soul_domain_model_abstractfragment (persistence_object_identifier) ON DELETE SET NULL");
		$this->addSql("CREATE UNIQUE INDEX UNIQ_288DD06D53A4BC5B ON famelo_soul_domain_model_soul (rootfragment)");
	}
}