<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20141009213321 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("CREATE TABLE famelo_soul_domain_model_partysoul (persistence_object_identifier VARCHAR(40) NOT NULL, PRIMARY KEY(persistence_object_identifier))");
		$this->addSql("ALTER TABLE famelo_soul_domain_model_partysoul ADD CONSTRAINT FK_EBCEEA9F47A46B0A FOREIGN KEY (persistence_object_identifier) REFERENCES famelo_soul_domain_model_soul (persistence_object_identifier) ON DELETE CASCADE");
		$this->addSql("ALTER TABLE famelo_soul_domain_model_abstractfragment DROP token");
		$this->addSql("ALTER TABLE famelo_soul_domain_model_soul ADD token VARCHAR(255) NOT NULL, ADD dtype VARCHAR(255) NOT NULL");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("DROP TABLE famelo_soul_domain_model_partysoul");
		$this->addSql("ALTER TABLE famelo_soul_domain_model_abstractfragment ADD token VARCHAR(255) NOT NULL");
		$this->addSql("ALTER TABLE famelo_soul_domain_model_soul DROP token, DROP dtype");
	}
}