-
  name: 'Soul routing'
  uriPattern: '{__soul}/{__soulFragment}/{@action}'
  # routeParts:
  #   '__soul':
  #     handler:   'Famelo\Soul\Routing\SoulRoutePartHandler'
  appendExceedingArguments: true