TYPO3:
  Flow:
    object:
      excludeClasses:
       'gedmo.doctrineextensions': ['.*']

    # security:
    #   enable: TRUE
    #   authentication:
    #     authenticationStrategy: oneToken
    #     providers:
    #       DefaultProvider:
    #         provider: '\Famelo\Soul\Security\SoulAwareUsernamePasswordProvider'
    #         entryPoint: 'WebRedirect'
    #         entryPointOptions:
    #           routeValues:
    #             '@action': 'index'
    #             '@controller': 'Standard'
    #             '@package': 'My.Package'

    # http:
    #   chain:
    #     'process':
    #       chain:
    #         'soulRouting':
    #           position: 'after routing'
    #           component: 'Famelo\Soul\Core\SoulRoutingComponent'